# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hydrakv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hydrakv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhydrakv.proto\x12\x02kv\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x0f\x43reateDBRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"Q\n\nSetRequest\x12\n\n\x02\x64\x62\x18\x01 \x01(\t\x12\x0e\n\x06\x61pikey\x18\x02 \x01(\t\x12\x0b\n\x03ttl\x18\x03 \x01(\x03\x12\x0b\n\x03key\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\t\"5\n\nGetRequest\x12\n\n\x02\x64\x62\x18\x01 \x01(\t\x12\x0e\n\x06\x61pikey\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\"8\n\rDeleteRequest\x12\n\n\x02\x64\x62\x18\x01 \x01(\t\x12\x0e\n\x06\x61pikey\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\"F\n\x0bIncrRequest\x12\n\n\x02\x64\x62\x18\x01 \x01(\t\x12\x0e\n\x06\x61pikey\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\t\"\x1b\n\rExistsRequest\x12\n\n\x02\x64\x62\x18\x01 \x01(\t\"\x18\n\nOKResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"Q\n\x10\x43reateDBResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61pikey\x18\x02 \x01(\t\x12\x0f\n\x07\x63reated\x18\x03 \x01(\x08\x12\x0e\n\x06\x65xists\x18\x04 \x01(\x08\"+\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\" \n\x0e\x45xistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xf7\x02\n\tKVService\x12\x35\n\x08\x43reateDB\x12\x13.kv.CreateDBRequest\x1a\x14.kv.CreateDBResponse\x12%\n\x03Set\x12\x0e.kv.SetRequest\x1a\x0e.kv.OKResponse\x12\'\n\x05SetNX\x12\x0e.kv.SetRequest\x1a\x0e.kv.OKResponse\x12\'\n\x04Incr\x12\x0f.kv.IncrRequest\x1a\x0e.kv.OKResponse\x12&\n\x03Get\x12\x0e.kv.GetRequest\x1a\x0f.kv.GetResponse\x12+\n\x06\x44\x65lete\x12\x11.kv.DeleteRequest\x1a\x0e.kv.OKResponse\x12/\n\x06\x45xists\x12\x11.kv.ExistsRequest\x1a\x12.kv.ExistsResponse\x12\x34\n\x06Health\x12\x16.google.protobuf.Empty\x1a\x12.kv.HealthResponseB\x14Z\x12hydrakv/proto/kvpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hydrakv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022hydrakv/proto/kvpb'
  _globals['_CREATEDBREQUEST']._serialized_start=50
  _globals['_CREATEDBREQUEST']._serialized_end=81
  _globals['_SETREQUEST']._serialized_start=83
  _globals['_SETREQUEST']._serialized_end=164
  _globals['_GETREQUEST']._serialized_start=166
  _globals['_GETREQUEST']._serialized_end=219
  _globals['_DELETEREQUEST']._serialized_start=221
  _globals['_DELETEREQUEST']._serialized_end=277
  _globals['_INCRREQUEST']._serialized_start=279
  _globals['_INCRREQUEST']._serialized_end=349
  _globals['_EXISTSREQUEST']._serialized_start=351
  _globals['_EXISTSREQUEST']._serialized_end=378
  _globals['_OKRESPONSE']._serialized_start=380
  _globals['_OKRESPONSE']._serialized_end=404
  _globals['_CREATEDBRESPONSE']._serialized_start=406
  _globals['_CREATEDBRESPONSE']._serialized_end=487
  _globals['_GETRESPONSE']._serialized_start=489
  _globals['_GETRESPONSE']._serialized_end=532
  _globals['_EXISTSRESPONSE']._serialized_start=534
  _globals['_EXISTSRESPONSE']._serialized_end=566
  _globals['_HEALTHRESPONSE']._serialized_start=568
  _globals['_HEALTHRESPONSE']._serialized_end=600
  _globals['_KVSERVICE']._serialized_start=603
  _globals['_KVSERVICE']._serialized_end=978
# @@protoc_insertion_point(module_scope)
