# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import hydrakv_pb2 as hydrakv__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hydrakv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVServiceStub(object):
    """===== Service =====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDB = channel.unary_unary(
                '/kv.KVService/CreateDB',
                request_serializer=hydrakv__pb2.CreateDBRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.CreateDBResponse.FromString,
                _registered_method=True)
        self.Set = channel.unary_unary(
                '/kv.KVService/Set',
                request_serializer=hydrakv__pb2.SetRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.OKResponse.FromString,
                _registered_method=True)
        self.SetNX = channel.unary_unary(
                '/kv.KVService/SetNX',
                request_serializer=hydrakv__pb2.SetRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.OKResponse.FromString,
                _registered_method=True)
        self.Incr = channel.unary_unary(
                '/kv.KVService/Incr',
                request_serializer=hydrakv__pb2.IncrRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.OKResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/kv.KVService/Get',
                request_serializer=hydrakv__pb2.GetRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/kv.KVService/Delete',
                request_serializer=hydrakv__pb2.DeleteRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.OKResponse.FromString,
                _registered_method=True)
        self.Exists = channel.unary_unary(
                '/kv.KVService/Exists',
                request_serializer=hydrakv__pb2.ExistsRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.ExistsResponse.FromString,
                _registered_method=True)
        self.FiFoLiFoDelete = channel.unary_unary(
                '/kv.KVService/FiFoLiFoDelete',
                request_serializer=hydrakv__pb2.FiFoLiFoDeleteRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.OKResponse.FromString,
                _registered_method=True)
        self.FiFoLiFoPush = channel.unary_unary(
                '/kv.KVService/FiFoLiFoPush',
                request_serializer=hydrakv__pb2.FiFoLiFoPushRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.OKResponse.FromString,
                _registered_method=True)
        self.FiFoLiFoFPop = channel.unary_unary(
                '/kv.KVService/FiFoLiFoFPop',
                request_serializer=hydrakv__pb2.FiFoLiFoPopRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.FiFoLiFoPopResponse.FromString,
                _registered_method=True)
        self.FiFoLiFoLPop = channel.unary_unary(
                '/kv.KVService/FiFoLiFoLPop',
                request_serializer=hydrakv__pb2.FiFoLiFoPopRequest.SerializeToString,
                response_deserializer=hydrakv__pb2.FiFoLiFoPopResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/kv.KVService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=hydrakv__pb2.HealthResponse.FromString,
                _registered_method=True)


class KVServiceServicer(object):
    """===== Service =====

    """

    def CreateDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Incr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FiFoLiFoDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FiFoLiFoPush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FiFoLiFoFPop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FiFoLiFoLPop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDB': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDB,
                    request_deserializer=hydrakv__pb2.CreateDBRequest.FromString,
                    response_serializer=hydrakv__pb2.CreateDBResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=hydrakv__pb2.SetRequest.FromString,
                    response_serializer=hydrakv__pb2.OKResponse.SerializeToString,
            ),
            'SetNX': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNX,
                    request_deserializer=hydrakv__pb2.SetRequest.FromString,
                    response_serializer=hydrakv__pb2.OKResponse.SerializeToString,
            ),
            'Incr': grpc.unary_unary_rpc_method_handler(
                    servicer.Incr,
                    request_deserializer=hydrakv__pb2.IncrRequest.FromString,
                    response_serializer=hydrakv__pb2.OKResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=hydrakv__pb2.GetRequest.FromString,
                    response_serializer=hydrakv__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=hydrakv__pb2.DeleteRequest.FromString,
                    response_serializer=hydrakv__pb2.OKResponse.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=hydrakv__pb2.ExistsRequest.FromString,
                    response_serializer=hydrakv__pb2.ExistsResponse.SerializeToString,
            ),
            'FiFoLiFoDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.FiFoLiFoDelete,
                    request_deserializer=hydrakv__pb2.FiFoLiFoDeleteRequest.FromString,
                    response_serializer=hydrakv__pb2.OKResponse.SerializeToString,
            ),
            'FiFoLiFoPush': grpc.unary_unary_rpc_method_handler(
                    servicer.FiFoLiFoPush,
                    request_deserializer=hydrakv__pb2.FiFoLiFoPushRequest.FromString,
                    response_serializer=hydrakv__pb2.OKResponse.SerializeToString,
            ),
            'FiFoLiFoFPop': grpc.unary_unary_rpc_method_handler(
                    servicer.FiFoLiFoFPop,
                    request_deserializer=hydrakv__pb2.FiFoLiFoPopRequest.FromString,
                    response_serializer=hydrakv__pb2.FiFoLiFoPopResponse.SerializeToString,
            ),
            'FiFoLiFoLPop': grpc.unary_unary_rpc_method_handler(
                    servicer.FiFoLiFoLPop,
                    request_deserializer=hydrakv__pb2.FiFoLiFoPopRequest.FromString,
                    response_serializer=hydrakv__pb2.FiFoLiFoPopResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=hydrakv__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kv.KVService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kv.KVService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVService(object):
    """===== Service =====

    """

    @staticmethod
    def CreateDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/CreateDB',
            hydrakv__pb2.CreateDBRequest.SerializeToString,
            hydrakv__pb2.CreateDBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Set',
            hydrakv__pb2.SetRequest.SerializeToString,
            hydrakv__pb2.OKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/SetNX',
            hydrakv__pb2.SetRequest.SerializeToString,
            hydrakv__pb2.OKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Incr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Incr',
            hydrakv__pb2.IncrRequest.SerializeToString,
            hydrakv__pb2.OKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Get',
            hydrakv__pb2.GetRequest.SerializeToString,
            hydrakv__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Delete',
            hydrakv__pb2.DeleteRequest.SerializeToString,
            hydrakv__pb2.OKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Exists',
            hydrakv__pb2.ExistsRequest.SerializeToString,
            hydrakv__pb2.ExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FiFoLiFoDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/FiFoLiFoDelete',
            hydrakv__pb2.FiFoLiFoDeleteRequest.SerializeToString,
            hydrakv__pb2.OKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FiFoLiFoPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/FiFoLiFoPush',
            hydrakv__pb2.FiFoLiFoPushRequest.SerializeToString,
            hydrakv__pb2.OKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FiFoLiFoFPop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/FiFoLiFoFPop',
            hydrakv__pb2.FiFoLiFoPopRequest.SerializeToString,
            hydrakv__pb2.FiFoLiFoPopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FiFoLiFoLPop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/FiFoLiFoLPop',
            hydrakv__pb2.FiFoLiFoPopRequest.SerializeToString,
            hydrakv__pb2.FiFoLiFoPopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            hydrakv__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
